"""Initial schema

Revision ID: 05a70339686a
Revises: 
Create Date: 2026-09-16 19:09:22.593139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a70339686a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('officer_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('material_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=128), nullable=False),
    sa.Column('code_a', sa.String(length=64), nullable=False),
    sa.Column('code_b', sa.String(length=64), nullable=False),
    sa.Column('embedding_similarity', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('safety_flags', sa.String(length=256), nullable=True),
    sa.Column('officer_decision', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_matches_code_a'), 'material_matches', ['code_a'], unique=False)
    op.create_index(op.f('ix_material_matches_code_b'), 'material_matches', ['code_b'], unique=False)
    op.create_index(op.f('ix_material_matches_id'), 'material_matches', ['id'], unique=False)
    op.create_index(op.f('ix_material_matches_match_id'), 'material_matches', ['match_id'], unique=True)
    op.create_index(op.f('ix_material_matches_verdict'), 'material_matches', ['verdict'], unique=False)
    op.create_table('materials_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('embedding_vector', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_embeddings_id'), 'materials_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_materials_embeddings_material_code'), 'materials_embeddings', ['material_code'], unique=True)
    op.create_table('materials_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('source_cpse', sa.String(length=32), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('material_type', sa.String(length=64), nullable=True),
    sa.Column('sub_type', sa.String(length=64), nullable=True),
    sa.Column('dimension_value', sa.Float(), nullable=True),
    sa.Column('dimension_unit', sa.String(length=16), nullable=True),
    sa.Column('schedule', sa.String(length=32), nullable=True),
    sa.Column('standard', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('pressure_rating', sa.String(length=32), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_text_cluster_id'), 'materials_text', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_materials_text_grade'), 'materials_text', ['grade'], unique=False)
    op.create_index(op.f('ix_materials_text_id'), 'materials_text', ['id'], unique=False)
    op.create_index(op.f('ix_materials_text_material_code'), 'materials_text', ['material_code'], unique=True)
    op.create_index(op.f('ix_materials_text_material_type'), 'materials_text', ['material_type'], unique=False)
    op.create_index(op.f('ix_materials_text_pressure_rating'), 'materials_text', ['pressure_rating'], unique=False)
    op.create_index(op.f('ix_materials_text_source_cpse'), 'materials_text', ['source_cpse'], unique=False)
    op.create_index(op.f('ix_materials_text_standard'), 'materials_text', ['standard'], unique=False)
    op.create_index(op.f('ix_materials_text_sub_type'), 'materials_text', ['sub_type'], unique=False)
    op.create_table('national_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnmc_code', sa.String(length=32), nullable=False),
    sa.Column('representative_description', sa.Text(), nullable=False),
    sa.Column('unspsc_code', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_materials_cnmc_code'), 'national_materials', ['cnmc_code'], unique=True)
    op.create_index(op.f('ix_national_materials_id'), 'national_materials', ['id'], unique=False)
    op.create_table('unspsc_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('unspsc_code', sa.String(length=32), nullable=False),
    sa.Column('unspsc_title', sa.String(length=256), nullable=False),
    sa.Column('commodity_category', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=True),
    sa.Column('mapping_rationale', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unspsc_mappings_id'), 'unspsc_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_unspsc_mappings_material_code'), 'unspsc_mappings', ['material_code'], unique=False)
    op.create_index(op.f('ix_unspsc_mappings_unspsc_code'), 'unspsc_mappings', ['unspsc_code'], unique=False)
    op.create_table('cpse_code_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_material_id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('source_cpse', sa.String(length=32), nullable=False),
    sa.Column('linked_by_match_id', sa.String(length=128), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_code'], ['materials_text.material_code'], ),
    sa.ForeignKeyConstraint(['national_material_id'], ['national_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpse_code_links_id'), 'cpse_code_links', ['id'], unique=False)
    op.create_index(op.f('ix_cpse_code_links_material_code'), 'cpse_code_links', ['material_code'], unique=False)
    op.create_index(op.f('ix_cpse_code_links_national_material_id'), 'cpse_code_links', ['national_material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpse_code_links_national_material_id'), table_name='cpse_code_links')
    op.drop_index(op.f('ix_cpse_code_links_material_code'), table_name='cpse_code_links')
    op.drop_index(op.f('ix_cpse_code_links_id'), table_name='cpse_code_links')
    op.drop_table('cpse_code_links')
    op.drop_index(op.f('ix_unspsc_mappings_unspsc_code'), table_name='unspsc_mappings')
    op.drop_index(op.f('ix_unspsc_mappings_material_code'), table_name='unspsc_mappings')
    op.drop_index(op.f('ix_unspsc_mappings_id'), table_name='unspsc_mappings')
    op.drop_table('unspsc_mappings')
    op.drop_index(op.f('ix_national_materials_id'), table_name='national_materials')
    op.drop_index(op.f('ix_national_materials_cnmc_code'), table_name='national_materials')
    op.drop_table('national_materials')
    op.drop_index(op.f('ix_materials_text_sub_type'), table_name='materials_text')
    op.drop_index(op.f('ix_materials_text_standard'), table_name='materials_text')
    op.drop_index(op.f('ix_materials_text_source_cpse'), table_name='materials_text')
    op.drop_index(op.f('ix_materials_text_pressure_rating'), table_name='materials_text')
    op.drop_index(op.f('ix_materials_text_material_type'), table_name='materials_text')
    op.drop_index(op.f('ix_materials_text_material_code'), table_name='materials_text')
    op.drop_index(op.f('ix_materials_text_id'), table_name='materials_text')
    op.drop_index(op.f('ix_materials_text_grade'), table_name='materials_text')
    op.drop_index(op.f('ix_materials_text_cluster_id'), table_name='materials_text')
    op.drop_table('materials_text')
    op.drop_index(op.f('ix_materials_embeddings_material_code'), table_name='materials_embeddings')
    op.drop_index(op.f('ix_materials_embeddings_id'), table_name='materials_embeddings')
    op.drop_table('materials_embeddings')
    op.drop_index(op.f('ix_material_matches_verdict'), table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_match_id'), table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_id'), table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_code_b'), table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_code_a'), table_name='material_matches')
    op.drop_table('material_matches')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
