"""Add ScoringAdjustment table

Revision ID: 9bb909ffbe82
Revises: 05a70339686a
Create Date: 2026-09-16 19:10:20.668923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb909ffbe82'
down_revision: Union[str, Sequence[str], None] = '05a70339686a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('old_high_threshold', sa.Float(), nullable=False),
    sa.Column('new_high_threshold', sa.Float(), nullable=False),
    sa.Column('old_medium_threshold', sa.Float(), nullable=False),
    sa.Column('new_medium_threshold', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_adjustments_id'), 'scoring_adjustments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_adjustments_id'), table_name='scoring_adjustments')
    op.drop_table('scoring_adjustments')
    # ### end Alembic commands ###
